export enum TypeBillRealTime {
  BOOKING = "BOOKING", SHIPPING = "SHIPPING",

  CHECKED = "CHECKED", CANCELLED = "CANCELLED",
  COMPELETED = "COMPELETED",

  // cho cộng tác viên
  BOOKING_SHPPING = "BOOKING_SHPPING",
}
